FuturaMkt\Entity\Product\Product:
  properties:
    category_id:
      - NotBlank: ~
      - NotNull: ~
    attributeGroups:
      - FuturaMkt\Constraints\HasAttributeName: {attrName: "listing_type_id", groups: [insert]}
