FuturaMkt\Entity\Product\Product:
  properties:
    category_id:
      - NotBlank: ~
      - NotNull: ~

FuturaMkt\Entity\Product\AttributeGroup:
  properties:
    attributeGroups:
      - All:
          -
